# Generated by Django 4.2.6 on 2024-02-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
