# Generated by Django 4.2.6 on 2024-02-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.post'),
        ),
    ]
