# Generated by Django 4.2.6 on 2024-02-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_userprofile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='post',
        ),
    ]
